<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.zxp.test.SeleniumTest" tests="7" time="125.610" ignored="0" failures="1" timestamp="04 五月 2018 08:07:07 GMT" skipped="0" hostname="DESKTOP-VVQ736U" errors="0">
  <testcase name="testChangeColor" time="27.238" classname="com.zxp.test.SeleniumTest"/>
  <testcase name="test1" time="2.749" classname="com.zxp.test.SeleniumTest"/>
  <testcase name="testFrame" time="55.993" classname="com.zxp.test.SeleniumTest"/>
  <testcase name="test3" time="18.120" classname="com.zxp.test.SeleniumTest">
    <failure type="java.lang.AssertionError" message="expected [华为 HUAWEI Mate 10 Pro移动联通电手机 宝石蓝 全网通6G+64G] but found [五一华为mate10 Pro直降430]">
      <![CDATA[java.lang.AssertionError: expected [华为 HUAWEI Mate 10 Pro移动联通电手机 宝石蓝 全网通6G+64G] but found [五一华为mate10 Pro直降430]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.zxp.test.SeleniumTest.test3(SeleniumTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="10.464" classname="com.zxp.test.SeleniumTest"/>
  <testcase name="testScript" time="9.082" classname="com.zxp.test.SeleniumTest"/>
  <testcase name="testAlert" time="1.964" classname="com.zxp.test.SeleniumTest"/>
</testsuite> <!-- com.zxp.test.SeleniumTest -->
